### PR TITLE
Fix jumping while standing on loose tile

### PR DESCRIPTION
**Pull request by nicolasbock**
Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>

### CODE REVIEW

**Comment by mprices** [comment]
Looks great! Being able to jump while on a falling tile is quite critical to the game play. I was wondering before why it was so difficult, it didn't occur to me that this was the reason.

**Review by mprices — APPROVED** [review]
Looks great! Being able to jump while on a falling tile is quite critical to the game play. I was wondering before why it was so difficult, it didn't occur to me that this was the reason.

**Comment by nicolasbock** [comment]
Yes me too. I blamed it on my age :wink:

**Comment by nicolasbock** [comment]
Closing in favor of #136

**Pull request closed without merging**
